from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlmodel import Session

from app.config import get_settings
from app.database import get_session
from app.models import PracticeSession, TrainingPlan
from app.services.coach import CoachService

router = APIRouter(prefix="/coach", tags=["coach"])


class GeneratePlanRequest(BaseModel):
    goal: str = Field(min_length=3)
    focus_patterns: str = ""
    duration_days: int = Field(default=7, ge=1, le=90)
    save: bool = True


class GenerateWorkoutRequest(BaseModel):
    goal: str = Field(min_length=3)
    focus: str = Field(min_length=2)
    plan_id: int | None = None
    save: bool = True


class HintRequest(BaseModel):
    problem: str = Field(min_length=10)
    current_attempt: str = ""
    level: int = Field(default=1, ge=1, le=3)


@router.post("/plans")
def generate_plan(
    payload: GeneratePlanRequest,
    session: Session = Depends(get_session),
) -> dict[str, object]:
    try:
        plan_text = CoachService(get_settings()).generate_plan(
            payload.goal,
            payload.focus_patterns,
            payload.duration_days,
        )
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Plan generation failed: {exc}") from exc

    plan: TrainingPlan | None = None
    if payload.save:
        plan = TrainingPlan(
            name=payload.goal[:80],
            goal=payload.goal,
            focus_patterns=payload.focus_patterns,
            duration_days=payload.duration_days,
            schedule_json=plan_text,
        )
        session.add(plan)
        session.commit()
        session.refresh(plan)

    return {"plan": plan, "generated": plan_text}


@router.post("/workouts")
def generate_workout(
    payload: GenerateWorkoutRequest,
    session: Session = Depends(get_session),
) -> dict[str, object]:
    try:
        workout_text = CoachService(get_settings()).generate_workout(
            payload.goal,
            payload.focus,
        )
    except Exception as exc:
        raise HTTPException(
            status_code=502, detail=f"Workout generation failed: {exc}"
        ) from exc

    practice_session: PracticeSession | None = None
    if payload.save:
        practice_session = PracticeSession(
            plan_id=payload.plan_id,
            status="planned",
            warm_up="Generated by coach",
            main_workout=workout_text,
            review="Review mistakes, time complexity, and reusable pattern notes.",
            reflection_prompt="What pattern signal will you recognize faster next time?",
        )
        session.add(practice_session)
        session.commit()
        session.refresh(practice_session)

    return {"practice_session": practice_session, "generated": workout_text}


@router.post("/hints")
def generate_hint(payload: HintRequest) -> dict[str, str | int]:
    try:
        hint = CoachService(get_settings()).generate_hint(
            payload.problem,
            payload.current_attempt,
            payload.level,
        )
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Hint generation failed: {exc}") from exc
    return {"level": payload.level, "hint": hint}
